version: '3.8'

services:
  my-spring-app:
    restart: always
    image: svetlindimitrov/nutrition_api:v1
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db

  mysql-db:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nutritionApi

networks:
  spring-app: