server:
  port: 8080

spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:secrets.properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/nutritionApi?createDatabaseIfNotExist=true
    username: root

security:
  api-secret-key: '${JWT_SECRET:writeYourSecretKeyWord}'
