spring:

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASS:12345}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/nutritionApi
    username: ${DB_USER:root}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

security:
  api-secret-key: '12345'
