spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASS:12345}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/nutritionApi
    username: ${DB_USER:root}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

jwt:
  expiration-time: 1800000 # 30 minutes in milliseconds

refresh-token:
  expiration-time: 2592000000 # 30 days in milliseconds

cors:
  allowed-origins: http://localhost:5173,http://localhost:8080