logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:12345}
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:nutritionApi}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
  jpa:
    hibernate:

      ddl-auto: update
    spring:
      jpa:
        show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
security:
  api-secret-key: ${JWT_SECRET:topSecret}
