spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASS:12345}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/nutritionApi
    username: ${DB_USER:root}
  sql:
    init:
      mode: always

security:
  api-secret-key: '12345'
