name: vue-client

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Run the workflow'
        required: true
  push:
    paths:
      - 'reactive_nutritionAPI/web/**'

jobs:
  vue-client-cicd:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name : Build && Deploy
      working-directory: ./reactive_nutritionAPI/web
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutritionapi-vue-client .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutritionapi-vue-client
